name: 刷步数

on:
  schedule:
    - cron: '44 10,12,14 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 添加全局权限配置（确保GitHub Token有权限）
    permissions:
      contents: read  # 允许读取仓库代码
      actions: read    # 允许读取Actions配置

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 升级到v4版本
        with:
          token: ${{ secrets.ACCESS_TOKEN }}  # 使用自定义Token（需提前配置）

      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y

      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 开始
        run: |
          pip3 install requests==2.32.3 urllib3==2.2.3  # 固定版本避免兼容性问题
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}' 
          open_get_weather='${{ secrets.OPEN_GET_WEATHER }}'
          area='${{ secrets.AREA }}'
          # 添加高德API Key环境变量
          export GAODE_API_KEY=${{ secrets.GAODE_API_KEY }}
          python3 main.py ${user} ${passwd} ${open_get_weather} ${area}
